### ISSUE TITLE
Signed apk error due to combination between Either an livedata

### ISSUE THREAD

**Issue by rdiaz82** [kategory/arrow#511]
Hi!
I'm using Either types in combination with LiveData doing something like this:

```
val requestResponse: LiveData<Either<String, LoginResponse>> = ApiManager.signIn(email, password)
        requestResponse.observeForever {
            if (it is Either.Right){
                it.b.user.save() //THE ERROR HAPPENS IN THIS LINE
                AuthenticationManager.saveToken(it.b.token)
                response.value = true.right()
            } else {
                val errorMessage:String = (it as Either.Left).a
                response.value = errorMessage.left()
            }

        }
```
At running time all works as expected but when I create a signed release version I'm getting the following error, anyway the signed file is created: 

`Error:java.lang.IllegalStateException: Recursive call in a lazy value under LockBasedStorageManager@4d091785 (<unknown creating class>)`

Any ideas how to solve it?
Thanks!

**Comment by pakoito** [comment]
I'd be surprised that this is related to Either, as you're not using any of the internal APIs. Let's check whether it's just that line. Try doing this:

```
val token: String? = it.fold({ it.token }, { null })
val user: User? = it.fold({ it.user }, { null })

if (token != null && user != null) {
   user.save() //THE ERROR HAPPENS IN THIS LINE
   AuthenticationManager.saveToken(token)
   response.value = true.right()
} else {
  // SOMETHING HERE JUST FOR TESTING
  "Error"
}
```
And see what happens.

**Comment by rdiaz82** [comment]
This is curious, I tried with the fold but token and user were not resolved inside the fold. I tried a simple approach:
```
val user = it.b.user
val token = it.b.token
user.save()
AuthenticationManager.saveToken(token)
```
With this approach the error disappear, from this class and appear in the activity which is observing the request. I'm getting the error now when I try to get the error message. I tried with the same approach but it doesn't work in this case and the error is still there ¬¬. Here is the other error:

```
viewModel.user.observe(this, Observer<Either<String, Boolean>> {
            it?.let {
                when (it) {
                    is Either.Right -> binding.user = AuthenticationManager.getCurrentUser()
                    is Either.Left -> {
                        textView.text = ""
                        val errorMessage:String = it.a <== ERROR HERE
                        Toast.makeText(this, "Error $errorMessage", Toast.LENGTH_SHORT).show()
                    }
                }
            }
        })
```
Any Idea?

**Comment by pakoito** [comment]
>This is curious, I tried with the fold but token and user were not resolved inside the fold.
I need a more in-depth discussion of what you mean with this. "Not resolved" means not available, or null, or the execution never continued?

>With this approach the error disappear, from this class and appear in the activity which is observing the request. I'm getting the error now when I try to get the error message. I tried with the same approach but it doesn't work in this case and the error is still there ¬¬. Here is the other error
Chacho, necesito entender ésto mejor. Pásate por el gitter y hablamos: gitter.im/kategory/Lobby

**Comment by pakoito** [comment]
After chatting with @rdiaz82 it seemed unrelated to the lib. Closing.
